//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11March2017Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public string adminEmail { get; set; }
        public string adminPassword { get; set; }
        public Nullable<int> adminID { get; set; }
    }
}
