//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11March2017Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage
    {
        public int ImageID { get; set; }
        public byte[] ImageFile { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> prod_ID { get; set; }
        public Nullable<int> vend_ID { get; set; }
        public string ImagePath { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
