//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11March2017Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
        }
    
        public int orderID { get; set; }
        public int vendorID { get; set; }
        public int orderStatus { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<double> totalOrderPrice { get; set; }
        public Nullable<double> orderRating { get; set; }
        public Nullable<System.DateTime> orderPlacedTime { get; set; }
        public string orderDelieveryAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblOrderStatu tblOrderStatu { get; set; }
    }
}
