//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11March2017Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVendor()
        {
            this.tblProducts = new HashSet<tblProduct>();
            this.tblImages = new HashSet<tblImage>();
        }
    
        public int vendorID { get; set; }
        public string vendorName { get; set; }
        public string vendorEmail { get; set; }
        public string vendorPassword { get; set; }
        public int vendorAge { get; set; }
        public string vendorAddress { get; set; }
        public string vendorPhone { get; set; }
        public int vendorGender { get; set; }
        public int vendorType { get; set; }
        public string vendorCNIC { get; set; }
    
        public virtual tblBusinessType tblBusinessType { get; set; }
        public virtual tblGender tblGender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImage> tblImages { get; set; }
    }
}
